aliases:
  1.png: get
  2.png: 不
  3.png: 冲
  4.png: 出发
  5.png: 呃
  6.png: 哦
  7.png: 哼
  8.png: 唉
  9.png: 嗨
  10.png: 嗯
  11.png: 妥
  12.png: 无语
  13.png: 晕
  14.png: 棒
  15.png: 泪
  16.png: 等待
chinese_name: 名画小黑奇遇记
english_name: ming-hua-xiao-hei-qi-yu-ji
source: 微信@罗小黑CAT
source_description: 表情包版权归原作者所有
tags: {}
