aliases:
  1.png: 我太难了
  2.png: 三点几啦
  3.png: 盯
  4.png: 加班
  5.png: 加油
  6.png: 好耶
  7.png: 点赞
  8.png: 饮茶先啦
  9.png: 兴奋
  10.png: 害羞
  11.png: 加鸡腿
  12.png: 打卡
  13.png: 再来亿遍
  14.png: 悠闲
  15.png: 晚安
  16.png: 摸鱼
chinese_name: 猫咪公寓
english_name: mao-mi-gong-yu
source: bilibili://user_center/vip/buy/191?appSubId=vipSticker
source_description: 表情包版权归原作者所有
tags: {}
