aliases:
  1.gif: biu
  2.gif: ok
  3.gif: wink
  4.gif: 冒出
  5.gif: 加载中
  6.gif: 听不懂
  7.gif: 吹刘海
  8.gif: 呜哇
  9.gif: 哼
  10.gif: 喝茶
  11.gif: 喷了
  12.gif: 嗯嗯
  13.gif: 困
  14.gif: 大脑过载
  15.gif: 头疼
  16.gif: 好
  17.gif: 好吃
  18.gif: 妥
  19.gif: 嫌弃
  20.gif: 害羞
  21.gif: 小孩别看
  22.gif: 崇拜
  23.gif: 干劲十足
  24.gif: 怒
  25.gif: 思考
  26.gif: 拍照
  27.gif: 拽
  28.gif: 挨打
  29.gif: 捂嘴
  30.gif: 捶桌1
  31.gif: 捶桌2
  32.gif: 搓手期待
  33.gif: 摸摸头
  34.gif: 擦汗
  35.gif: 收到
  36.gif: 暗中观察
  37.gif: 有猫腻
  38.gif: 气鼓鼓
  39.gif: 泪
  40.gif: 爽
  41.gif: 笑容消失
  42.gif: 累
  43.gif: 给你花花
  44.gif: 美滋滋
  45.gif: 耶
  46.gif: 臭屁
  47.gif: 馋
  48.gif: 鼓掌
chinese_name: 罗小黑的生活
english_name: luo-xiao-hei-de-sheng-huo
source: 微信@罗小黑CAT
source_description: 表情包版权归原作者所有
tags: {}
