aliases:
  1.png: 啊
  2.png: 沉思
  3.png: 干杯
  4.png: 给你币
  5.png: 给你心心
  6.png: 无奈
  7.png: 好耶
  8.png: 加油
  9.png: 惊讶
  10.png: 拉手手
  11.png: 期待
  12.png: 亲亲
  13.png: 甜的
  14.png: 偷瞄
  15.png: 兔饼
  16.png: 晚安
  17.png: 呜呜
  18.png: 洗澡
  19.png: 幸运
  20.png: 在家
chinese_name: 懒懒兔
english_name: lan-lan-tu
source: https://www.bilibili.com/h5/mall/equity-link/collect-home?item_id=37808&isdiy=0&part=emoji_package&from=emoji&f_source=garb&vmid=451090261&native.theme=1&navhide=1
source_description: 表情包版权归原作者所有
tags: {}
