aliases:
  ok.webp: 'ok'
  jushou.webp: '举手'
  maibao.webp: '买爆'
  youhuiquan.webp: '优惠券'
  touxiao.webp: '偷笑'
  zaijian.webp: '再见'
  diaoxie.webp: '凋谢'
  jiayou.webp: '加油'
  gouyin.webp: '勾引'
  kelian.webp: '可怜'
  tanqi.webp: '叹气'
  chigua.webp: '吃瓜'
  heshi.webp: '合十'
  tongkuan.webp: '同款'
  tushetou.webp: '吐舌头'
  xiangyou.webp: '向右'
  baji.webp: '吧唧'
  wa.webp: '哇'
  kure.webp: '哭惹'
  henaicha.webp: '喝奶茶'
  daxiao.webp: '大笑'
  shiwang.webp: '失望'
  haixiu.webp: '害羞'
  kaixiang.webp: '开箱'
  ruo.webp: '弱'
  deyi.webp: '得意'
  weixiao.webp: '微笑'
  jingkong.webp: '惊恐'
  daka.webp: '打卡'
  chelian.webp: '扯脸'
  fuqiang.webp: '扶墙'
  zhuakuang.webp: '抓狂'
  koubi.webp: '抠鼻'
  baoquan.webp: '抱拳'
  bacao.webp: '拔草'
  yongbao.webp: '拥抱'
  quantou.webp: '拳头'
  wulian.webp: '捂脸'
  tandian.webp: '探店'
  woshou.webp: '握手'
  xieyan.webp: '斜眼'
  xingxing.webp: '星星'
  anzhongguancha.webp: '暗中观察'
  hanyan.webp: '汗颜'
  paidui.webp: '派对'
  huo.webp: '火'
  zhadan.webp: '炸弹'
  dianzan.webp: '点赞'
  goutou.webp: '狗头'
  meigui.webp: '玫瑰'
  shengqi.webp: '生气'
  zhoumei.webp: '皱眉'
  shuijue.webp: '睡觉'
  shihua.webp: '石化'
  zhongcao.webp: '种草'
  xiaoku.webp: '笑哭'
  ye.webp: '耶'
  zipai.webp: '自拍'
  sese.webp: '色色'
  mengmengda.webp: '萌萌哒'
  qingyouhao.webp: '请友好'
  qingwenming.webp: '请文明'
  gouwuche.webp: '购物车'
  zan.webp: '赞'
  dunhouxu.webp: '蹲后续'
  yujinxiang.webp: '郁金香'
  bishi.webp: '鄙视'
  feiwen.webp: '飞吻'
  huangjinshu.webp: '黄金薯'
  heishuwenhao.webp: '黑薯问号'
  guzhang.webp: '鼓掌'
chinese_name: 小红书
english_name: rednote
source: xiaohongshu.com
source_description: 由小可整理，表情包版权归原作者所有
tags: {}
