aliases:
  1.webp: ok
  10.webp: 强
  11.webp: 当古人
  12.webp: 戳一下
  13.webp: 戳戳
  14.webp: 拍一下
  15.webp: 摸
  16.webp: 比心
  17.webp: 点个赞
  18.webp: 点点
  19.webp: 狗头
  2.webp: ye
  20.webp: 猫
  21.webp: 猴
  22.webp: 福到了
  23.webp: 立
  24.webp: 藏狐
  25.webp: 赞个点
  26.webp: 起
  27.webp: 趴趴
  28.webp: 蹄
  29.webp: 送花
  3.webp: 一
  30.webp: 问号
  31.webp: 马
  32.webp: 马上有钱
  33.webp: 马不
  34.webp: 鱼头
  35.webp: 鱼尾
  4.webp: 不太冷
  5.webp: 伸手
  6.webp: 停
  7.webp: 凹
  8.webp: 嗷
  9.webp: 坏笑
chinese_name: BiliBili25年度表情包
english_name: bili-25-nian-du-biao-qing-bao
source: https://www.bilibili.com/
source_description: 版权归哔哩哔哩所有
tags: {}
