aliases:
  ablobcat_fu_drawing_impatience.webp: ''
  blobcat_fu_2024.png: ''
  blobcat_fu_2025.png: ''
  blobcat_fu_2026.png: ''
  blobcat_fu_2027.png: ''
  blobcat_fu_2028.png: ''
  blobcat_fu_2029.png: ''
  blobcat_fu_2030.png: ''
  blobcat_fu_I_feel_like_death.webp: ''
  blobcat_fu_ahe.webp: ''
  blobcat_fu_be_dying.webp: ''
  blobcat_fu_be_gameover.webp: ''
  blobcat_fu_beam.png: ''
  blobcat_fu_beam2.png: ''
  blobcat_fu_black.webp: ''
  blobcat_fu_blue.png: ''
  blobcat_fu_bounce.gif: ''
  blobcat_fu_center.png: ''
  blobcat_fu_center2.png: ''
  blobcat_fu_center2_middlefingers.png: ''
  blobcat_fu_center_middlefingers.png: ''
  blobcat_fu_cute.png: ''
  blobcat_fu_despair.webp: ''
  blobcat_fu_dodge.webp: ''
  blobcat_fu_doubt.webp: ''
  blobcat_fu_doubt_middlefinger.png: ''
  blobcat_fu_drawing.webp: ''
  blobcat_fu_drawing_impatience.webp: ''
  blobcat_fu_drawing_impatience2.webp: ''
  blobcat_fu_drawing_normal.webp: ''
  blobcat_fu_drawing_yabai.webp: ''
  blobcat_fu_drawing_yabai2.webp: ''
  blobcat_fu_excitement.webp: ''
  blobcat_fu_explode.gif: ''
  blobcat_fu_fearful.webp: ''
  blobcat_fu_fearful2.webp: ''
  blobcat_fu_fearful_c.png: ''
  blobcat_fu_fearful_middlefinger.webp: ''
  blobcat_fu_fingerguns.png: ''
  blobcat_fu_fingerguns2.png: ''
  blobcat_fu_fury.webp: ''
  blobcat_fu_gazepero.webp: ''
  blobcat_fu_gazepero2.webp: ''
  blobcat_fu_gazepero2_middlefinger.png: ''
  blobcat_fu_gazepero_middlefinger.png: ''
  blobcat_fu_green.webp: ''
  blobcat_fu_gun.png: ''
  blobcat_fu_gun2.png: ''
  blobcat_fu_gun3.png: ''
  blobcat_fu_gun4.png: ''
  blobcat_fu_gun5.png: ''
  blobcat_fu_gun6.webp: ''
  blobcat_fu_gun7.png: ''
  blobcat_fu_happy.webp: ''
  blobcat_fu_happy2.webp: ''
  blobcat_fu_happy3.webp: ''
  blobcat_fu_impatience.webp: ''
  blobcat_fu_jax.webp: ''
  blobcat_fu_jax2.webp: ''
  blobcat_fu_kiss.webp: ''
  blobcat_fu_knife.png: ''
  blobcat_fu_knife2.png: ''
  blobcat_fu_knife3.png: ''
  blobcat_fu_knife4.png: ''
  blobcat_fu_knife5.png: ''
  blobcat_fu_knife_b1.png: ''
  blobcat_fu_knife_b10.webp: ''
  blobcat_fu_knife_b11.webp: ''
  blobcat_fu_knife_b12.webp: ''
  blobcat_fu_knife_b13.webp: ''
  blobcat_fu_knife_b14.png: ''
  blobcat_fu_knife_b15.webp: ''
  blobcat_fu_knife_b16.webp: ''
  blobcat_fu_knife_b2.png: ''
  blobcat_fu_knife_b3.png: ''
  blobcat_fu_knife_b4.png: ''
  blobcat_fu_knife_b5.png: ''
  blobcat_fu_knife_b6.png: ''
  blobcat_fu_knife_b7.png: ''
  blobcat_fu_knife_b8.png: ''
  blobcat_fu_knife_b9.png: ''
  blobcat_fu_long_back.png: ''
  blobcat_fu_long_back2.png: ''
  blobcat_fu_long_center.png: ''
  blobcat_fu_long_left.png: ''
  blobcat_fu_long_right.png: ''
  blobcat_fu_lookingyou.png: ''
  blobcat_fu_lookingyou2.png: ''
  blobcat_fu_lookingyou2_c.png: ''
  blobcat_fu_lookingyou2_c_middlefinger.png: ''
  blobcat_fu_lookingyou2_c_middlefingers.png: ''
  blobcat_fu_lookingyou3.png: ''
  blobcat_fu_lookingyou3_c.png: ''
  blobcat_fu_lookingyou3_c_middlefingers.png: ''
  blobcat_fu_lookingyou3_middlefinger.png: ''
  blobcat_fu_lookingyou3b.webp: ''
  blobcat_fu_lookingyou4.png: ''
  blobcat_fu_lookingyou4_c.png: ''
  blobcat_fu_lookingyou4_c_middlefingers.png: ''
  blobcat_fu_lookingyou5.png: ''
  blobcat_fu_lookingyou5_c.png: ''
  blobcat_fu_lookingyou5_c_middlefingers.png: ''
  blobcat_fu_lookingyou6_c.png: ''
  blobcat_fu_lookingyou6_c_middlefingers.png: ''
  blobcat_fu_lookingyou_c.png: ''
  blobcat_fu_lookingyou_c_middlefingers.png: ''
  blobcat_fu_lookingyou_middlefinger.png: ''
  blobcat_fu_mad.png: ''
  blobcat_fu_mad2.png: ''
  blobcat_fu_mad2_middlefinger.png: ''
  blobcat_fu_mad2b.png: ''
  blobcat_fu_mad2b_middlefinger.png: ''
  blobcat_fu_mad3.png: ''
  blobcat_fu_mad3b.png: ''
  blobcat_fu_mad4.png: ''
  blobcat_fu_mad4_middlefinger.webp: ''
  blobcat_fu_mad4b.png: ''
  blobcat_fu_mad5.png: ''
  blobcat_fu_mad5_middlefinger.webp: ''
  blobcat_fu_mad_middlefinger.png: ''
  blobcat_fu_mad_zoom.webp: ''
  blobcat_fu_mad_zoom2.webp: ''
  blobcat_fu_mad_zoom3.webp: ''
  blobcat_fu_mad_zoom4.webp: ''
  blobcat_fu_mad_zoom5.webp: ''
  blobcat_fu_mad_zoom6.webp: ''
  blobcat_fu_madb.png: ''
  blobcat_fu_make_fun.png: ''
  blobcat_fu_make_fun2.webp: ''
  blobcat_fu_make_fun_a.webp: ''
  blobcat_fu_make_fun_middlefinger.png: ''
  blobcat_fu_melt.png: ''
  blobcat_fu_melt2.webp: ''
  blobcat_fu_melt3.webp: ''
  blobcat_fu_melt4.webp: ''
  blobcat_fu_melt5.png: ''
  blobcat_fu_melt5_middlefinger.png: ''
  blobcat_fu_mesugaki.webp: ''
  blobcat_fu_mesugaki2.webp: ''
  blobcat_fu_middlefinger.png: ''
  blobcat_fu_monster.webp: ''
  blobcat_fu_normal.png: ''
  blobcat_fu_normal2.png: ''
  blobcat_fu_orange.png: ''
  blobcat_fu_pet_be_dying.gif: ''
  blobcat_fu_pet_blue.gif: ''
  blobcat_fu_pet_fearful.gif: ''
  blobcat_fu_pet_happy.gif: ''
  blobcat_fu_pet_i_feel_like_death.gif: ''
  blobcat_fu_pet_mad3.gif: ''
  blobcat_fu_pet_mad_zoom.gif: ''
  blobcat_fu_pet_melt2.gif: ''
  blobcat_fu_pet_melt4.gif: ''
  blobcat_fu_pet_normal.gif: ''
  blobcat_fu_pet_normal2.gif: ''
  blobcat_fu_pet_sorry.gif: ''
  blobcat_fu_pet_sorry2.gif: ''
  blobcat_fu_pet_sorry3.gif: ''
  blobcat_fu_pet_sorry4.gif: ''
  blobcat_fu_pet_surprised3.gif: ''
  blobcat_fu_pet_yabai.gif: ''
  blobcat_fu_pink.png: ''
  blobcat_fu_pomupu.png: ''
  blobcat_fu_pomupu2.webp: ''
  blobcat_fu_purple.png: ''
  blobcat_fu_shakenup.webp: ''
  blobcat_fu_smile.webp: ''
  blobcat_fu_smile2.webp: ''
  blobcat_fu_smile_middlefinger.webp: ''
  blobcat_fu_smilepero.webp: ''
  blobcat_fu_sorry.png: ''
  blobcat_fu_sorry2.webp: ''
  blobcat_fu_sorry3.png: ''
  blobcat_fu_sorry4.png: ''
  blobcat_fu_speechless.png: ''
  blobcat_fu_surprised.png: ''
  blobcat_fu_surprised2.png: ''
  blobcat_fu_surprised2_middlefinger.png: ''
  blobcat_fu_surprised3.png: ''
  blobcat_fu_surprised3_middlefinger.png: ''
  blobcat_fu_surprised4.png: ''
  blobcat_fu_surprised4b.webp: ''
  blobcat_fu_surprised5.webp: ''
  blobcat_fu_sweatflip.webp: ''
  blobcat_fu_sweatflip_middlefinger.webp: ''
  blobcat_fu_thinking.png: ''
  blobcat_fu_thinking2.png: ''
  blobcat_fu_thinking3.png: ''
  blobcat_fu_umm.webp: ''
  blobcat_fu_unknown.webp: ''
  blobcat_fu_unknown2.webp: ''
  blobcat_fu_uwu.webp: ''
  blobcat_fu_uwu_middlefinger.webp: ''
  blobcat_fu_uwupero.webp: ''
  blobcat_fu_whatsthis.png: ''
  blobcat_fu_whatsthis_middlefinger.png: ''
  blobcat_fu_wow.webp: ''
  blobcat_fu_yabai.png: ''
  blobcat_fu_yabai_middlefinger.png: ''
  blobcat_fu_yummy.webp: ''
  blobcat_fu_yummy2.webp: ''
  blobcat_fu_yummy2_middlefinger.webp: ''
chinese_name: blobcat_fu
english_name: blobcat_fu
source: 网络
source_description: 由 Summer 整理
tags: {}
