aliases:
  1.png: 棒棒
  2.png: 比心
  3.png: 别惹我
  4.png: 馋馋
  5.png: 开心
  6.png: 困
  7.png: 冒泡
  8.png: 上号
  9.png: 生气
  10.png: 贴贴
  11.png: 听不懂
  12.png: 偷看
  13.png: 偷笑
  14.png: 哇
  15.png: 晚安
  16.png: 委屈
  17.png: 无语
  18.png: 吓
  19.png: 耶
  20.png: 疑问
chinese_name: 罗小黑战记
english_name: luo-xiao-hei-zhan-ji
source: https://www.bilibili.com/h5/mall/equity-link/collect-home?item_id=5122&isdiy=0&part=emoji_package&from=emoji&f_source=garb&native.theme=1&navhide=1
source_description: 表情包版权归原作者所有
tags: {}
