aliases:
  1.png: 软乎乎
  2.png: 棒棒
  3.png: 阿打
  4.png: 刀子
  5.png: 好吃
  6.png: 没有烦恼
  7.png: 观察
  8.png: 捡垃圾
  9.png: 回来啦
  10.png: 胖哭了
  11.png: 若有所思
  12.png: 干饭
  13.png: 你欺负我
  14.png: 心虚
  15.png: 走了
  16.png: 稀罕你
  17.png: 委屈
  18.png: 甜
  19.png: 休息
  20.png: 心软软
chinese_name: 懒懒兔收藏集
english_name: lan-lan-tu-shou-cang-ji
source: https://www.bilibili.com/h5/mall/digital-card/home?act_id=100129&from=emoji&f_source=garb&-Abrowser=live&hybrid_set_header=2&navhide=1&anchor_task=1
source_description: 表情包版权归原作者所有
tags: {}
