aliases:
  0.gif: 胡乱地拍  
  1.gif: 加油  
  2.gif: 赞  
  3.gif: 流口水  
  4.gif: 螂来了  
  5.gif: 问号  
  6.gif: 泪奔  
  7.gif: 击毙  
  8.gif: 很凶  
  9.gif: 拿来  
  10.gif: 泡泡  
  11.gif: 嗷呜  
  12.gif: 精神稳定  
  13.gif: 没事  
  14.gif: 戳手  
  15.gif: 干饭
chinese_name: 小熊虫3
english_name: xiaoxiongchong3
source: 微信@小熊虫com
source_description: null
tags: {}
