aliases:
  1.png: Go！
  2.png: Huh？
  3.png: OK
  4.png: Yo！
  5.png: 擦汗
  6.png: 戳戳
  7.png: 大笑
  8.png: 低气压
  9.png: 盯
  10.png: 慌张
  11.png: 加载
  12.png: 惊
  13.png: 喵...
  14.png: 摸下巴
  15.png: 抹泪
  16.png: 你说啥
  17.png: 期待
  18.png: 思考
  19.png: 贴贴
  20.png: 委屈
  21.png: 喜欢
  22.png: 耶
  23.png: 再会
  24.png: 在吗
  25.png: 跩
chinese_name: 神探罗小黑
english_name: shen-tan-luo-xiao-hei
source: https://www.bilibili.com/h5/mall/equity-link/collect-home?item_id=1752479029001&isdiy=0&part=emoji_package&from=emoji&f_source=garb&native.theme=1&navhide=1
source_description: 表情包版权归原作者所有
tags: {}
